### ISSUE TITLE
ModuleNotFoundError: No module named 'control'

### ISSUE THREAD

**Issue by wangshub** [haruki1526/LeggedRobot#1]
```
>> python walking_with_preview_control.py
pybullet build time: Apr  8 2020 00:34:41
Traceback (most recent call last):
  File "walking_with_preview_control.py", line 5, in <module>
    from walking_generator import PreviewControl
  File "./LeggedRobotsForBullet/bipedal/walking_generator.py", line 4, in <module>
    import control
ModuleNotFoundError: No module named 'control'
```

missing the `control` dare solver for zmp preview controller

@haruki1526

**Comment by wangshub** [comment]
solved by `pip install control`
